# Generated by Django 4.2.4 on 2023-08-14 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Feeding',
            new_name='Birdseed',
        ),
        migrations.RenameField(
            model_name='birdseed',
            old_name='meal',
            new_name='seed',
        ),
        migrations.RenameField(
            model_name='finch',
            old_name='color',
            new_name='breed',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='type',
        ),
        migrations.AddField(
            model_name='finch',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
